# Generated by Django 5.0.3 on 2024-04-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_chef_facebook_chef_instagram_chef_twitter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
