# Generated by Django 5.0.3 on 2024-04-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_menu_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="slug",
        ),
    ]
