# Generated by Django 5.0.3 on 2024-04-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_menu_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="price",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
