# Generated by Django 5.0.3 on 2024-04-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_menu_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.CharField(default=5, max_length=500),
        ),
    ]
