# Generated by Django 5.0.3 on 2024-04-23 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_menu_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="price",
        ),
    ]
