# Generated by Django 5.0.3 on 2024-04-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_menu_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.CharField(default=5, max_length=500),
        ),
    ]
