# Generated by Django 5.0.3 on 2024-04-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_remove_menu_price_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactinfo",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="post",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="stars",
        ),
        migrations.AddField(
            model_name="feedback",
            name="role",
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
