# Generated by Django 5.0.3 on 2024-04-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_feedback_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactInfo",
        ),
    ]
