# Generated by Django 5.0.3 on 2024-04-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
