# Generated by Django 5.0.3 on 2024-04-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_delete_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("slug", models.CharField(max_length=500)),
                ("email", models.CharField(max_length=500)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("request", models.TextField(blank=True)),
                ("quantity", models.FloatField(default=1)),
                ("checkout", models.BooleanField(default=False)),
            ],
        ),
    ]
